# Interval skeniranja sistema u milisekundama
monitor.interval=3000
# Putanja do fajla gde se cuvaju informacije procesa
mapping.file=data/process_info.json
# Interval za automatsko snimanje snapshot-a u CSV (u sekundama)
snapshot.interval=60
# Fiksni intervali za snimanje snapshot-a u CSV (u formatu hh:mm:ss)
snapshot.fixed_time_1=15:30:24
snapshot.fixed_time_2=15:30:28
